version: '3.8'

services:
  etl:
    build: .
    container_name: etl_pipeline
    depends_on:
      - kafka
      - postgres
      - mongo
      - clickhouse
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      POSTGRES_HOST: postgres
      MONGO_HOST: mongo
      CLICKHOUSE_HOST: clickhouse
    volumes:
      - ./etl:/app/etl
    restart: unless-stopped


  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.3
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.3.3
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test_db

  mongo:
    image: mongo:6
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse_final_task
    restart: always
    ports:
      - "9123:8123" # Поменял порт, тк уже крутится один CH для другого проекта по этим портам
      - "10000:9000" # Поменял порт, тк уже крутится один CH для другого проекта по этим портам
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      CLICKHOUSE_USER: user
      CLICKHOUSE_PASSWORD: strongpassword
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000" # Порт для веб-интерфейса Grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin # Логин администратора Grafana
      - GF_SECURITY_ADMIN_PASSWORD=admin # Пароль администратора Grafana
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - clickhouse

volumes:
  pgdata:
  clickhouse_data:
  mongodb_data:
  grafana_data: